#!/usr/bin/env node
// Quake Town content: map packs.
//   maps-lq  LibreQuake lqdm1–13 compiled BSPs + .lit (BSD-3-Clause), as released in v0.09-beta
//   maps-qt  our original maps, generated by content/maps/<name>.mjs and compiled with ericw-tools
// Each pack carries maps.json: [{ name, title, author, modes, players: [min, max] }].
// Copyright (C) 2026 Quake Town contributors. GPL-2.0-or-later.
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fetchAll, PATHS, ROOT, CACHE } from './fetch.mjs';
import { parseBsp } from './lib/bsp.mjs';
import { writePack, upToDate, stamp, inputsKey, BUILD_DIR } from './lib/packs.mjs';

export const QT_MAPS = ['qt_aero', 'qt_tower', 'qt_fort'];

// Suggested modes / player ranges for the LibreQuake maps (titles come from each BSP's
// worldspawn message, the author from its _credits key).
const LQ = {
  lqdm1: { modes: ['duel', '2on2', 'ffa'], players: [2, 6] },
  lqdm2: { modes: ['duel', '2on2', 'ffa'], players: [2, 6] },
  lqdm3: { modes: ['ffa', '2on2', '4on4'], players: [4, 12] },
  lqdm4: { modes: ['duel', '2on2', 'ffa'], players: [2, 8] },
  lqdm5: { modes: ['ffa', '2on2', '4on4'], players: [4, 10] },
  lqdm6: { modes: ['ffa', '2on2'], players: [2, 8] },
  lqdm7: { modes: ['duel', '2on2', 'ffa'], players: [2, 6] },
  lqdm8: { modes: ['duel', '2on2', 'ffa'], players: [2, 8] },
  lqdm9: { modes: ['ffa', '2on2', '4on4'], players: [4, 10] },
  lqdm10: { modes: ['ffa', '2on2', '4on4'], players: [4, 10] },
  lqdm11: { modes: ['duel', '2on2', 'ffa'], players: [2, 8] },
  lqdm12: { modes: ['ffa', '2on2'], players: [2, 8] },
  lqdm13: { modes: ['duel', '2on2', 'ffa'], players: [2, 8] },
};

export async function buildMapsLq() {
  await fetchAll();
  const files = new Map();
  const srcs = [];
  for (const n of Object.keys(LQ)) {
    for (const ext of ['bsp', 'lit']) {
      const p = join(PATHS.lq, 'maps', `${n}.${ext}`);
      if (existsSync(p)) srcs.push(p);
    }
  }
  const docs = ['COPYING', 'CREDITS'].map((d) => join(PATHS.lq, 'docs', d));
  const key = inputsKey([...srcs, ...docs, import.meta.filename, join(ROOT, 'tools/content/lib/archive.mjs')]);
  const prev = upToDate('maps-lq', key);
  if (prev) return prev;
  const maps = [];
  for (const p of srcs) files.set(`maps/${p.split('/').pop()}`, readFileSync(p));
  for (const [name, meta] of Object.entries(LQ)) {
    const bsp = parseBsp(readFileSync(join(PATHS.lq, 'maps', `${name}.bsp`)));
    const ws = bsp.ents[0] || {};
    maps.push({ name, title: (ws.message || name).trim(), author: (ws._credits || 'LibreQuake contributors').trim(), modes: meta.modes, players: meta.players });
  }
  files.set('maps.json', Buffer.from(JSON.stringify(maps, null, 1) + '\n'));
  files.set('licenses/librequake-copying.txt', readFileSync(docs[0]));
  files.set('licenses/librequake-credits.txt', readFileSync(docs[1]));
  files.set('licenses/readme.txt', Buffer.from('LibreQuake deathmatch maps lqdm1-lqdm13 (v0.09-beta), by ZungryWare and the LibreQuake contributors.\nBSD-3-Clause: see librequake-copying.txt.\n'));
  const entry = writePack('maps-lq', 'maps', files, { title: 'LibreQuake deathmatch maps', maps });
  stamp('maps-lq', key);
  console.log(`maps-lq: ${maps.length} maps, ${(entry.bytes / 1024).toFixed(0)} KB`);
  return entry;
}

export async function buildMapsQt({ fast = false, only = null } = {}) {
  await fetchAll();
  const { compileMap, MAPS_OUT } = await import('./compile-map.mjs');
  const libFiles = readdirSync(join(ROOT, 'content/maps/lib')).map((f) => join(ROOT, 'content/maps/lib', f));
  const toolFiles = ['compile-map.mjs', 'check-map.mjs', 'lib/bsp.mjs'].map((f) => join(ROOT, 'tools/content', f));
  const pin = readFileSync(join(CACHE, 'fetch.stamp.json'), 'utf8');
  const results = [];
  mkdirSync(BUILD_DIR, { recursive: true });
  for (const name of QT_MAPS) {
    const src = join(ROOT, 'content/maps', `${name}.mjs`);
    if (!existsSync(src)) { console.log(`maps-qt: ${name} has no generator yet, skipped`); continue; }
    const key = inputsKey([src, ...libFiles, ...toolFiles], pin + (fast ? 'fast' : 'full'));
    const st = join(BUILD_DIR, `map-${name}.stamp`), sj = join(BUILD_DIR, `map-${name}.json`);
    let res;
    if ((only && !only.includes(name)) || (existsSync(st) && readFileSync(st, 'utf8') === key && existsSync(sj) && existsSync(join(MAPS_OUT, `${name}.bsp`)))) {
      if (!existsSync(sj)) continue;
      res = JSON.parse(readFileSync(sj, 'utf8'));
    } else {
      const t0 = Date.now();
      const r = await compileMap(name, { fast });
      if (!r.check.ok) throw new Error(`${name} failed playability checks:\n${r.check.report}`);
      res = { name, info: r.info, stats: r.stats, check: r.check.report, ms: Date.now() - t0 };
      writeFileSync(sj, JSON.stringify(res, null, 1));
      writeFileSync(st, key);
      console.log(`compiled ${name} in ${((Date.now() - t0) / 1000).toFixed(1)} s: ${JSON.stringify(r.stats)}`);
    }
    results.push(res);
  }
  if (!results.length) return null;
  const packKey = inputsKey(results.flatMap((r) => [join(MAPS_OUT, `${r.name}.bsp`), join(MAPS_OUT, `${r.name}.lit`)]), import.meta.filename + JSON.stringify(results.map((r) => r.info)));
  const prev = upToDate('maps-qt', packKey);
  if (prev) return { entry: prev, results };
  const files = new Map();
  const maps = [];
  for (const r of results) {
    files.set(`maps/${r.name}.bsp`, readFileSync(join(MAPS_OUT, `${r.name}.bsp`)));
    const lit = join(MAPS_OUT, `${r.name}.lit`);
    if (existsSync(lit)) files.set(`maps/${r.name}.lit`, readFileSync(lit));
    const i = r.info;
    maps.push({ name: i.name, title: i.title, author: i.author, modes: i.modes, players: i.players });
  }
  if (!maps.length) return null;
  files.set('maps.json', Buffer.from(JSON.stringify(maps, null, 1) + '\n'));
  files.set('licenses/readme.txt', Buffer.from(
`Quake Town original maps (${maps.map((m) => m.name).join(', ')}).
Layouts: generated by content/maps/*.mjs in the Quake Town source (GPL-2.0-or-later), compiled
with ericw-tools. Embedded textures: LibreQuake v0.09-beta, BSD-3-Clause (see the base pack's
licenses/librequake-copying.txt).
`));
  const entry = writePack('maps-qt', 'maps', files, { title: 'Quake Town maps', maps });
  stamp('maps-qt', packKey);
  console.log(`maps-qt: ${maps.length} maps, ${(entry.bytes / 1024).toFixed(0)} KB`);
  return { entry, results };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const fast = process.argv.includes('--fast');
  const only = process.argv.filter((a) => /^qt_/.test(a));
  await buildMapsLq();
  await buildMapsQt({ fast, only: only.length ? only : null });
}
