#!/usr/bin/env node
// `npm run build:content`: fetch pinned inputs, build base / maps-lq / maps-qt packs, write
// public/packs/index.json (DESIGN.md "Content packs"). Every step is stamp-cached, so a run
// with nothing changed is a fast no-op.
//   --fast   quick map compiles (vis -fast, light without -extra4/bounce) for iteration
// Copyright (C) 2026 Quake Town contributors. GPL-2.0-or-later.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fetchAll, ROOT, PATHS, PINS } from './fetch.mjs';
import { mkdirSync } from 'node:fs';
import { buildBase } from './build-base.mjs';
import { buildMapsLq, buildMapsQt } from './build-maps.mjs';
import { PACKS_DIR } from './lib/packs.mjs';
import { sha256, zipEntries } from './lib/archive.mjs';

/** the mod part's pack: mod/qtdm/build/pack.json if present, else scan public/packs/qtdm-*.pk3 */
function modEntry() {
  const pj = join(ROOT, 'mod/qtdm/build/pack.json');
  if (existsSync(pj)) {
    const e = JSON.parse(readFileSync(pj, 'utf8'));
    if (e.file && existsSync(join(PACKS_DIR, e.file))) return { kind: 'mod', ...e };
  }
  const f = existsSync(PACKS_DIR) ? readdirSync(PACKS_DIR).filter((x) => /^qtdm-[0-9a-f]{12}\.pk3$/.test(x)).sort() : [];
  if (!f.length) return null;
  const bytes = readFileSync(join(PACKS_DIR, f[f.length - 1]));
  return { id: sha256(bytes), name: 'qtdm', kind: 'mod', file: f[f.length - 1], bytes: bytes.length, files: [...zipEntries(bytes).keys()].filter((n) => !n.endsWith('/')).sort() };
}

/** assets-licenses/: LibreQuake notices + ASSET-LICENSES.txt with per-pack and per-map credits */
function writeLicenses(index) {
  const dir = join(ROOT, 'assets-licenses');
  mkdirSync(dir, { recursive: true });
  const put = (name, data) => {
    const p = join(dir, name);
    if (!existsSync(p) || !readFileSync(p).equals(Buffer.from(data))) writeFileSync(p, data);
  };
  for (const [src, dst] of [['COPYING', 'LibreQuake-COPYING.txt'], ['CREDITS', 'LibreQuake-CREDITS.txt'], ['README-IMPORTANT-LICENCE-INFO', 'LibreQuake-README-IMPORTANT-LICENCE-INFO.txt']]) {
    put(dst, readFileSync(join(PATHS.lq, 'docs', src)));
  }
  const L = [];
  L.push('Quake Town - game data licences', '================================', '');
  L.push('Quake Town\'s code is GPL-2.0-or-later (LICENSE). The game data it ships is listed here.');
  L.push('"QUAKE" is a trademark of id Software / ZeniMax; Quake Town is not affiliated with them.');
  L.push('No id Software data is shipped. Players may load their own pak0.pak/pak1.pak; those stay in their browser.', '');
  L.push('LibreQuake v0.09-beta  https://github.com/lavenderdotpet/LibreQuake');
  L.push('  Models, textures, sounds, gfx and the lqdm1-lqdm13 maps: BSD-3-Clause, see LibreQuake-COPYING.txt;');
  L.push('  contributors: LibreQuake-CREDITS.txt. (LibreQuake\'s QuakeC/progs.dat and pop.lmp are GPL-2 and are NOT shipped.)');
  L.push(`  Pinned download: ${PINS.lqFull.url} sha256 ${PINS.lqFull.sha256}`);
  L.push(`  Texture WADs used to compile our maps: ${PINS.lqDev.url} sha256 ${PINS.lqDev.sha256}`, '');
  for (const e of index) {
    L.push(`Pack ${e.file} (${e.kind}, ${Math.round(e.bytes / 1024)} KB, sha256 ${e.id})`);
    if (e.kind === 'base') {
      L.push('  LibreQuake models/sounds/gfx subset (BSD-3-Clause). WAV files are re-encoded: metadata chunks');
      L.push('  dropped and rates above 22050 Hz resampled to 22050 Hz (loop points kept).');
      L.push('  progs/flag.mdl: original Quake Town work (generated by content/models/flag.mjs), BSD-3-Clause.');
    } else if (e.kind === 'maps') {
      for (const m of e.maps ?? []) L.push(`  maps/${m.name}.bsp  "${m.title}" by ${m.author}`);
      if (e.name === 'maps-lq') L.push('  BSD-3-Clause (LibreQuake), shipped as released (compiled BSP + .lit).');
      else {
        L.push('  Layouts: Quake Town, generated by content/maps/*.mjs (GPL-2.0-or-later source; the BSP output is ours).');
        L.push('  Compiled with ericw-tools 2.0.0-alpha11 (build-time tool, not shipped). Embedded textures: LibreQuake, BSD-3-Clause.');
      }
    } else if (e.kind === 'mod') {
      L.push('  QuakeC mod compiled from mod/qtdm (port of id Software\'s qw-qc, GPL-2.0-or-later).');
    }
    L.push('');
  }
  put('ASSET-LICENSES.txt', L.join('\n'));
}

export async function buildContent({ fast = false } = {}) {
  const t0 = Date.now();
  await fetchAll();
  const base = await buildBase();
  const lq = await buildMapsLq();
  const qt = await buildMapsQt({ fast });
  const mod = modEntry();
  const index = [base, qt?.entry, lq, mod].filter(Boolean).map((e) => {
    const o = { id: e.id, name: e.name, kind: e.kind, file: e.file, bytes: e.bytes, files: e.files };
    if (e.title) o.title = e.title;
    if (e.maps) o.maps = e.maps;
    return o;
  });
  writeLicenses(index);
  const json = JSON.stringify(index, null, 1) + '\n';
  const out = join(PACKS_DIR, 'index.json');
  if (!existsSync(out) || readFileSync(out, 'utf8') !== json) writeFileSync(out, json);
  const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
  console.log(`build:content ${((Date.now() - t0) / 1000).toFixed(1)} s: ` + index.map((e) => `${e.file} ${kb(e.bytes)}`).join(', '));
  return index;
}

if (import.meta.url === `file://${process.argv[1]}`) await buildContent({ fast: process.argv.includes('--fast') });
