#!/usr/bin/env node
// Quake Town — builds the default mod (mod/qtdm) into public/packs/qtdm-<sha12>.pk3.
//
//   node tools/qc/build-mod.mjs            (npm run build:mod)
//
// 1. finds the QuakeC compiler: $QCC, else /app/data/home/quake-ref/tools/fteqcc,
//    else fteqcc / gmqcc on PATH (see tools/qc/README.md to build one);
// 2. writes mod/qtdm/build/qtcfg.qc (the CTF flag model: progs/flag.mdl when a
//    content pack has one, else progs/backpack.mdl as a stand-in);
// 3. compiles mod/qtdm/progs.src -> mod/qtdm/build/qwprogs.dat (zero errors,
//    QW progs version 6, CRC 54730 checked);
// 4. packs qwprogs.dat + qtdm.txt into a deterministic zip (sorted entries,
//    fixed timestamps) public/packs/qtdm-<sha12>.pk3, removes older qtdm-*.pk3,
//    and writes mod/qtdm/build/pack.json ({ id, name, kind, file, bytes, files }).
//
// Copyright (C) 2026 Quake Town contributors. GPL-2.0-or-later.

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { zipSync } from 'fflate';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const MOD = path.join(ROOT, 'mod/qtdm');
const BUILD = path.join(MOD, 'build');
const PACKS = path.join(ROOT, 'public/packs');
const DEFAULT_QCC = '/app/data/home/quake-ref/tools/fteqcc';
const QW_PROGS_VERSION = 6;
const QW_PROGHEADER_CRC = 54730;
// 1980-01-01 is the earliest zip (DOS) time; any fixed instant keeps the bytes stable.
const ZIP_MTIME = new Date(Date.UTC(2026, 0, 1, 0, 0, 0));

function fail(msg) {
  console.error(`build-mod: ${msg}`);
  process.exit(1);
}

function onPath(name) {
  for (const dir of (process.env.PATH || '').split(path.delimiter)) {
    const p = path.join(dir, name);
    try {
      fs.accessSync(p, fs.constants.X_OK);
      return p;
    } catch {}
  }
  return null;
}

function findCompiler() {
  if (process.env.QCC) {
    if (!fs.existsSync(process.env.QCC)) fail(`QCC=${process.env.QCC} does not exist`);
    return process.env.QCC;
  }
  if (fs.existsSync(DEFAULT_QCC)) return DEFAULT_QCC;
  const p = onPath('fteqcc') || onPath('fteqcc64') || onPath('gmqcc');
  if (p) return p;
  fail(
    'no QuakeC compiler found.\n' +
      `  Looked at $QCC, ${DEFAULT_QCC}, and fteqcc/gmqcc on PATH.\n` +
      '  Build fteqcc as described in tools/qc/README.md, or set QCC=/path/to/fteqcc.'
  );
}

// Does any content pack (or content source) carry progs/flag.mdl?
function haveFlagModel() {
  if (process.env.QT_FLAG_MODEL === '0') return false;
  if (process.env.QT_FLAG_MODEL === '1') return true;
  const index = path.join(PACKS, 'index.json');
  if (fs.existsSync(index)) {
    try {
      const packs = JSON.parse(fs.readFileSync(index, 'utf8'));
      for (const p of packs) {
        if (p.kind !== 'mod' && Array.isArray(p.files) && p.files.includes('progs/flag.mdl')) return true;
      }
    } catch {}
  }
  const stack = [path.join(ROOT, 'content')];
  while (stack.length) {
    const dir = stack.pop();
    let ents = [];
    try {
      ents = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const e of ents) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) stack.push(p);
      else if (e.name === 'flag.mdl' && path.basename(dir) === 'progs') return true;
    }
  }
  return false;
}

function writeConfig(flagReal) {
  const qc =
    '// generated by tools/qc/build-mod.mjs - do not edit\n' +
    `string QT_FLAG_MODEL = "${flagReal ? 'progs/flag.mdl' : 'progs/backpack.mdl'}";\n` +
    `float QT_FLAG_REAL = ${flagReal ? 1 : 0};\n`;
  fs.writeFileSync(path.join(BUILD, 'qtcfg.qc'), qc);
}

function compile(qcc) {
  const isGm = path.basename(qcc).startsWith('gmqcc');
  const args = isGm
    ? ['-std=fteqcc', '-fftepp', '-fno-short-logic', 'progs.src']
    : ['-Tq1', '-srcfile', 'progs.src'];
  const r = spawnSync(qcc, args, { cwd: MOD, encoding: 'utf8' });
  if (r.error) fail(`cannot run ${qcc}: ${r.error.message}`);
  const out = `${r.stdout || ''}${r.stderr || ''}`;
  const ok = r.status === 0;
  const lines = out.split('\n');
  const errors = lines.filter((l) => /\berror\b/i.test(l) && !/\b0 errors?\b/i.test(l));
  if (process.env.QC_VERBOSE) console.log(out);
  const warnings = lines.filter((l) => /\bwarning\b/i.test(l));
  if (!ok || errors.length) {
    console.error(out);
    fail(`compile failed (${errors.length} error lines)`);
  }
  return { out, warnings };
}

function checkProgs(buf) {
  const version = buf.readInt32LE(0);
  const crc = buf.readInt32LE(4);
  if (version !== QW_PROGS_VERSION) fail(`progs version ${version}, expected ${QW_PROGS_VERSION}`);
  if (crc !== QW_PROGHEADER_CRC) fail(`progs CRC ${crc}, expected QW ${QW_PROGHEADER_CRC} (system defs changed?)`);
  return { version, crc };
}

function main() {
  fs.mkdirSync(BUILD, { recursive: true });
  const qcc = findCompiler();
  const flagReal = haveFlagModel();
  writeConfig(flagReal);

  const progsPath = path.join(BUILD, 'qwprogs.dat');
  fs.rmSync(progsPath, { force: true });
  const { warnings } = compile(qcc);
  if (!fs.existsSync(progsPath)) fail('the compiler wrote no build/qwprogs.dat');
  const progs = fs.readFileSync(progsPath);
  checkProgs(progs);

  const txt = fs.readFileSync(path.join(MOD, 'qtdm.txt'));
  const files = { 'qtdm.txt': txt, 'qwprogs.dat': progs };
  const names = Object.keys(files).sort();
  const entries = {};
  for (const n of names) entries[n] = [new Uint8Array(files[n]), { level: 9, mtime: ZIP_MTIME }];
  const zip = Buffer.from(zipSync(entries));
  const sha = createHash('sha256').update(zip).digest('hex');
  const file = `qtdm-${sha.slice(0, 12)}.pk3`;

  fs.mkdirSync(PACKS, { recursive: true });
  for (const f of fs.readdirSync(PACKS)) {
    if (/^qtdm-[0-9a-f]{12}\.pk3$/.test(f) && f !== file) fs.rmSync(path.join(PACKS, f));
  }
  fs.writeFileSync(path.join(PACKS, file), zip);

  const pack = { id: sha, name: 'qtdm', kind: 'mod', file: `packs/${file}`, bytes: zip.length, files: names };
  fs.writeFileSync(path.join(BUILD, 'pack.json'), JSON.stringify(pack, null, 2) + '\n');

  console.log(
    `build-mod: ${path.relative(ROOT, progsPath)} ${(progs.length / 1024).toFixed(1)} KB ` +
      `(${warnings.length} warnings, compiler ${path.basename(qcc)}, flag model ${flagReal ? 'progs/flag.mdl' : 'progs/backpack.mdl (stand-in)'})`
  );
  console.log(`build-mod: public/packs/${file} ${(zip.length / 1024).toFixed(1)} KB sha256 ${sha}`);
}

main();
